language: android
android:
  components:
    - android-28
    - build-tools-28.0.3

env:
  global:
   # install timeout in minutes (2 minutes by default)
    - ADB_INSTALL_TIMEOUT=8

# Run assemble, unit tests, and create coverage report
before_install:
  - chmod +x gradlew
script:
  - ./gradlew clean assembleDebug assembleRelease